### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by popleyi** [Cvedia/cvedia-cli#1]
Hi,

is there any installation guidelines I can use. Many thanks for your help.

**Comment by aescarcha** [comment]
Hi popleyi,

Thats a very good question :) we're working on one now. Meanwhile, here's [the Dockerfile](https://github.com/aescarcha/cvedia-cli/blob/master/docker/cvedia-cli/Dockerfile) that I'm using to run the project on my fork branch. It may have some non-needed dependencies, but it gets the project running for me, and you can use it as a guide for installing it manually.

If you have any more doubt, answer here and I'll do my best to help you.

Cheers!

**Comment by popleyi** [comment]
Thanks for your reply. I will try.
