### ISSUE TITLE
installation fault

### ISSUE THREAD

**Issue by gyxoned** [Cvedia/cvedia-cli#11]
When I run make in cvedia-cli folder, I got these errors:

cvedia-hdf5writer.o: In function `Hdf5Writer::BeginWriting()':
/usr/src/cvedia/cvedia-cli/src/hdf5writer.cpp:140: undefined reference to `H5::H5File::openFile(std::string const&, unsigned int, H5::FileAccPropList const&)'
/usr/src/cvedia/cvedia-cli/src/hdf5writer.cpp:143: undefined reference to `H5::H5File::H5File(std::string const&, unsigned int, H5::FileCreatPropList const&, H5::FileAccPropList const&)'
cvedia-hdf5writer.o: In function `Hdf5Writer::AppendEntry(H5::DataSet*, void*, unsigned long long, H5::DataType const&)':
/usr/src/cvedia/cvedia-cli/src/hdf5writer.cpp:327: undefined reference to `H5::DataSet::read(std::string&, H5::DataType const&, H5::DataSpace const&, H5::DataSpace const&, H5::DSetMemXferPropList const&) const'
cvedia-hdf5writer.o: In function `Hdf5Writer::WriteData(Metadata*)':
/usr/src/cvedia/cvedia-cli/src/hdf5writer.cpp:229: undefined reference to `H5::CommonFG::createDataSet(std::string const&, H5::DataType const&, H5::DataSpace const&, H5::DSetCreatPropList const&) const'
cvedia-hdf5writer.o: In function `Hdf5Writer::CheckIntegrity(std::string)':
/usr/src/cvedia/cvedia-cli/src/hdf5writer.cpp:354: undefined reference to `H5::H5File::H5File(std::string const&, unsigned int, H5::FileCreatPropList const&, H5::FileAccPropList const&)'
/usr/src/cvedia/cvedia-cli/src/hdf5writer.cpp:355: undefined reference to `H5::CommonFG::openDataSet(std::string const&) const'
/usr/src/cvedia/cvedia-cli/src/hdf5writer.cpp:373: undefined reference to `H5::DataSet::read(std::string&, H5::DataType const&, H5::DataSpace const&, H5::DataSpace const&, H5::DSetMemXferPropList const&) const'
collect2: error: ld returned 1 exit status
Makefile:387: recipe for target 'cvedia' failed
make[2]: *** [cvedia] Error 1
make[2]: Leaving directory '/usr/src/cvedia/cvedia-cli/src'
Makefile:380: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/src/cvedia/cvedia-cli'
Makefile:321: recipe for target 'all' failed
make: *** [all] Error 2

Could you give me some help?

**Comment by aescarcha** [comment]
Hi gyxoned, what OS are you using? did you follow all the steps on README? We could help you better if you gave us the full trace through [pastebin](https://pastebin.com/).

In the meantime, if you're not going to use HDF5, when running configure add the flag --wihout-hdf5

    LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial CFLAGS=-I/usr/include/hdf5/serial ./configure --without-hdf5

**Comment by rorph** [comment]
@gyxoned We've added more install options, including a docker setup, and scripts to auto compile it. Let us know if you still having problems.
