### ISSUE TITLE
keyword is not visible at the https://cvedia.com/ui/camelyon-16

### ISSUE THREAD

**Issue by min6434** [Cvedia/cvedia-cli#13]
At the tutorial, when you tries to create a filter you can see what kinds of labels are there.
However when I type " Image.Label  = " nothing is visible.
How can I check what labels the project got?
![image](https://cloud.githubusercontent.com/assets/25948850/25369170/fd7ab0c6-29bc-11e7-98ba-cb1c55b92e0f.png)

**Comment by rorph** [comment]
@min6434 The autocomplete service was broken for a few days, it's back to work now. Let us know if you still have issues.
