### ISSUE TITLE
Cvidea takes forever to browse the camelyon16 dataset 

### ISSUE THREAD

**Issue by xtarx** [Cvedia/cvedia-cli#15]
[Cvedia camelyon16 dataset ](https://cvedia.com/browse/camelyon-16) link takes forever to browse the data. I have tried on 3 different machines using both Chrome & Firefox.

![image](https://user-images.githubusercontent.com/1085352/31587103-c203b52c-b1db-11e7-8925-b3e305483ea2.png)

**Comment by rorph** [comment]
@xtarx We fixed this a couple days ago, let me know if you still having issues.
