### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by sullivak-kyra** [Cvedia/cvedia-cli#9]
I'm having some troubles getting a build to work. The line 
```
ACLOCAL_PATH="/usr/src/cvedia/cvedia-cli" autoreconf -if
```
fails unless I also install automake. After doing this, ./configure fails with:
```
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/usr/src/cvedia/cvedia-cli':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
In config.log
```
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
configure:3668: $? = 0
configure:3657: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3668: $? = 1
configure:3657: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3668: $? = 1
configure:3688: checking whether the C compiler works
configure:3710: gcc  -I  conftest.c  >&5
gcc: fatal error: no input files
compilation terminated.
configure:3714: $? = 1
configure:3752: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "cvedia"
| #define PACKAGE_TARNAME "cvedia"
| #define PACKAGE_VERSION "0.0.1"
| #define PACKAGE_STRING "cvedia 0.0.1"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "cvedia"
| #define VERSION "0.0.1"
| /* end confdefs.h.  */
```

After that I tried building the Dockerfile in docker/cvedia-cli and got
```
Step 38/45 : WORKDIR /var/www/cvedia-cli
 ---> 9cc786251466
Removing intermediate container f9fcaab65353
Step 39/45 : RUN ACLOCAL_PATH="/var/www/cvedia-cli" autoreconf -if
 ---> Running in 71ac72f2972b
autoreconf: 'configure.ac' or 'configure.in' is required
The command '/bin/sh -c ACLOCAL_PATH="/var/www/cvedia-cli" autoreconf -if' returned a non-zero code: 1
```

Any suggestions? Thanks!

**Comment by aescarcha** [comment]
Hi sullivak-kyra, did you follow our install instructions step by step on a clean Ubuntu 16.04?
Installing **autoconf** should install **automake** by default, so the missing package is very weird.

    apt-get install autoconf
    ...
    The following NEW packages will be installed:
      autoconf automake autotools-dev ifupdown iproute2 isc-dhcp-client isc-dhcp-common libatm1 libdns-export162 libgdbm3 libisc-export160 libmnl0 libperl5.22
  libsigsegv2 libxtables11 m4 netbase perl perl-modules-5.22 rename

Also please do:

    apt-get update && apt-get upgrade

And try again.

Thank you for your feedback!

**Comment by sullivak-kyra** [comment]
Ah, I had --no-install-recommends to keep things small and tidy; removing that makes it work, thanks!
